#!/bin/sh
# 
# Copyright (c) 2016, Search Solution Corporation. All rights reserved.
# 
# Redistribution and use in source and binary forms, with or without 
# modification, are permitted provided that the following conditions are met:
# 
#   * Redistributions of source code must retain the above copyright notice, 
#     this list of conditions and the following disclaimer.
# 
#   * Redistributions in binary form must reproduce the above copyright 
#     notice, this list of conditions and the following disclaimer in 
#     the documentation and/or other materials provided with the distribution.
# 
#   * Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products 
#     derived from this software without specific prior written permission.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, 
# INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE 
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, 
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR 
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE 
# USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE. 
#

export CTP_HOME=$(cd $(dirname $(readlink -f $0))/../..; pwd)
local_svn_source_home=
curDir=`pwd`

function usage()
{
    echo ""
    echo "Usage: $0 -f <from source path>"
    echo ""
}


if [ $# -eq 0 ];then
    usage
    exit 1
fi

while getopts "f:h:" opt; do
      case $opt in
      f)
         local_svn_source_home="$OPTARG"
         ;;
      \?)
         usage
         exit 1
         ;;
      esac
done

[ ! -d "$local_svn_source_home" ] && echo "please confirm your local_svn_source_home parameter!" && exit 0


# Get svn account permission
svnUser=`ini.sh $CTP_HOME/conf/dailyqa.conf "svn.user"`
svnPwd=`ini.sh $CTP_HOME/conf/dailyqa.conf "svn.pwd"`
svnAccountParameters="--username $svnUser --password $svnPwd --no-auth-cache --non-interactive "

# Clean up
cd ${local_svn_source_home}
svn st ${svnAccountParameters} |grep '~' |awk '{print $NF}' |xargs -i rm -rf {}
svn st ${svnAccountParameters} |grep '^M' |awk '{print $NF}' |xargs -i rm -rf {}
svn st ${svnAccountParameters} |grep '!' |awk '{print $NF}' |grep -v "\\." |xargs -i rm -rf {}
svn cleanup .
svn revert -R -q .
svn st ${svnAccountParameters} |grep '?' |awk '{print $NF}' |xargs -i rm -rf {}

# Do case update
echo ""
echo "=== Start do case update ==="
svn up ${svnAccountParameters}
echo ""
echo "=== End to case update ==="

cd $curDir