#!/bin/bash
# 
# Copyright (c) 2016, Search Solution Corporation. All rights reserved.
# 
# Redistribution and use in source and binary forms, with or without 
# modification, are permitted provided that the following conditions are met:
# 
#   * Redistributions of source code must retain the above copyright notice, 
#     this list of conditions and the following disclaimer.
# 
#   * Redistributions in binary form must reproduce the above copyright 
#     notice, this list of conditions and the following disclaimer in 
#     the documentation and/or other materials provided with the distribution.
# 
#   * Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products 
#     derived from this software without specific prior written permission.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, 
# INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE 
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, 
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR 
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE 
# USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE. 
#
export CTP_HOME=$(cd $(dirname $(readlink -f $0))/../..; pwd)

build_home=
buildId=
category=
from=
coverage_controller_home=
coverage_controller_host=
coverage_controller_user=
coverage_controller_port=
coverage_controller_cc4c_home=
coverage_controller_proxy_host=
coverage_controller_proxy_user=
coverage_controller_proxy_port=

lcov_data_name=
allParams=$@

usage()
{
    echo "Usage: `basename $0` -h=source directory;
                               -n=build number;
                               -c=test category;"
    exit 1
}

if [ $# -eq 0 ]
then
  usage
        exit
fi

while [ $# -ne 0 ];do
        case $1 in
                -h)
                        shift
                build_home=$1
                ;;
                -n)
                        shift
                buildId=$1
                ;;
                -c)
                        shift
                category=$1
                ;;
        esac
        shift
done

function goToInstallationDirectory()
{
    if [ "$CUBRID" ]
    then
        cd $CUBRID
        if [ $? -eq 0 ];then
                cd ..
        else
                cd $HOME
        fi
    else
        cd $HOME
    fi
}

function collectCoverage()
{
      curDir=`pwd`
      
      srcFolder="cubrid-${buildId}"
      if [ !"$build_home" ]
      then
     	   goToInstallationDirectory
    	   cd build/${srcFolder}
      else
           cd $build_home/${srcFolder}
      fi
      
      rm -rf *.lcov
      chmod 755 ${CTP_HOME}/common/gcov/gcov 
      coverage_controller_home=`sh ${CTP_HOME}/bin/ini.sh coverage.conf coverage_controller_home`
      coverage_controller_host=`sh ${CTP_HOME}/bin/ini.sh coverage.conf coverage_controller_host`
      coverage_controller_user=`sh ${CTP_HOME}/bin/ini.sh coverage.conf coverage_controller_user`
      coverage_controller_port=`sh ${CTP_HOME}/bin/ini.sh coverage.conf coverage_controller_port`
      coverage_controller_proxy_host=`sh ${CTP_HOME}/bin/ini.sh coverage.conf coverage_controller_proxy_host`
      coverage_controller_proxy_user=`sh ${CTP_HOME}/bin/ini.sh coverage.conf coverage_controller_proxy_user`
      coverage_controller_proxy_port=`sh ${CTP_HOME}/bin/ini.sh coverage.conf coverage_controller_proxy_port`
      coverage_controller_pwd=`sh ${CTP_HOME}/bin/ini.sh ${CTP_HOME}/conf/common.conf coverage_controller_pwd`
      if [ ! "$coverage_controller_pwd" ];then
	 coverage_controller_pwd=`sh ${CTP_HOME}/bin/ini.sh ${CTP_HOME}/conf/common.conf default_ssh_pwd`
      fi
      coverage_controller_cc4c_home=`sh ${CTP_HOME}/bin/ini.sh coverage.conf coverage_controller_cc4c_home`
      
      lcov --gcov-tool=${CTP_HOME}/common/gcov/gcov  -d . -c -t "cubrid" -o cubrid_o.lcov --rc geninfo_adjust_src_path="${coverage_controller_home} => $HOME"
      tStamp=`date '+%Y%m%d%H%M%s'`
      host_name=`hostname -s`
      lcov_data_name="cubrid_[${category}]_${USER}-${host_name}_${tStamp}.lcov"
      mv cubrid_o.lcov ${lcov_data_name}

      cd $curDir
}

function uploadResult()
{
   curDir=`pwd`
   srcFolder="cubrid-${buildId}"
   if [ !"$build_home" ]
   then
        goToInstallationDirectory
        cd build/${srcFolder}
   else
    cd $build_home/${srcFolder}
   fi

   run_upload -from ${lcov_data_name} -user "$coverage_controller_user" -password "$coverage_controller_pwd" -host "$coverage_controller_host" -port "$coverage_controller_port" --proxy-host="$coverage_controller_proxy_host" --proxy-user="$coverage_controller_proxy_user" --proxy-port="$coverage_controller_proxy_port" -to "${coverage_controller_cc4c_home}/result/${buildId}/new"
   run_remote_script -user "$coverage_controller_user" -password "$coverage_controller_pwd" -host "$coverage_controller_host" -port "$coverage_controller_port" --proxy-host="$coverage_controller_proxy_host" --proxy-user="$coverage_controller_proxy_user" --proxy-port="$coverage_controller_proxy_port" -c "cd ${coverage_controller_cc4c_home}/result/${buildId}/new; echo ${lcov_data_name} >${lcov_data_name}.info"
   cd - $curDir
   echo UPLOAD `date '+%Y%m%d%H%M%s'` ${allParams} >> $HOME/.qacoverage

}

collectCoverage
uploadResult
