name: github-checks
on: 
  pull_request:
    branches:
      - develop
      -'feature/**'
jobs:
  code-style:
    name: code-style
    runs-on: ubuntu-20.04
    env:
      working-directory: .github/workflows
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '8'
      - id: files
        uses: jitterbit/get-changed-files@v1
        continue-on-error: true
      - name: Check code style
        id: stylecheck
        run: |
          for f in ${{ steps.files.outputs.added_modified }}; do
            ${{ env.working-directory }}/codestyle.sh ${f}
          done 
          git diff | tee gitdiff
          test ! -s gitdiff # is empty? yes: 0 no: 1
      - name: Suggest code changes
        if: ${{ failure() }}
        uses: reviewdog/action-suggester@v1
        with:
          tool_name: code-style (indent, astyle, google-java-format)
